import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });

    const { reportIds, recipients, sentBy } = await req.json();
    if (!reportIds?.length || !recipients?.length) {
      return Response.json({ error: 'reportIds and recipients are required' }, { status: 400 });
    }

    const reports = await Promise.all(
      reportIds.map(id => base44.entities.Report.filter({ id }))
    );
    const flatReports = reports.flat();

    // Build email HTML
    const vehicleRows = flatReports.map(r => `
      <tr>
        <td style="padding:10px;border-bottom:1px solid #eee;font-weight:600">${r.itemName}</td>
        <td style="padding:10px;border-bottom:1px solid #eee">${r.action || '—'}</td>
        <td style="padding:10px;border-bottom:1px solid #eee">${r.branch || '—'}</td>
        <td style="padding:10px;border-bottom:1px solid #eee">${r.askingPrice ? `$${r.askingPrice.toLocaleString()}` : '—'}</td>
        <td style="padding:10px;border-bottom:1px solid #eee">${r.meetingNote || r.comments || '—'}</td>
      </tr>
    `).join('');

    const html = `
      <div style="font-family:sans-serif;max-width:700px;margin:0 auto">
        <h2 style="color:#1e293b;border-bottom:2px solid #f5a623;padding-bottom:8px">Fleet Review — Disposition Decisions</h2>
        <p style="color:#64748b;font-size:14px">Sent by: ${sentBy}</p>
        <table style="width:100%;border-collapse:collapse;font-size:14px;margin-top:16px">
          <thead>
            <tr style="background:#f8fafc">
              <th style="padding:10px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase">Vehicle</th>
              <th style="padding:10px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase">Action</th>
              <th style="padding:10px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase">Branch</th>
              <th style="padding:10px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase">Asking Price</th>
              <th style="padding:10px;text-align:left;font-size:12px;color:#64748b;text-transform:uppercase">Notes</th>
            </tr>
          </thead>
          <tbody>${vehicleRows}</tbody>
        </table>
        <p style="color:#94a3b8;font-size:12px;margin-top:24px">Generated by AIR Fleet Review</p>
      </div>
    `;

    const RESEND_API_KEY = Deno.env.get('RESEND_API_KEY');
    await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'AIR Fleet Review <noreply@theprojectair.com>',
        to: recipients,
        subject: `Fleet Review — ${flatReports.length} Vehicle${flatReports.length !== 1 ? 's' : ''} (${new Date().toLocaleDateString()})`,
        html,
      }),
    });

    return Response.json({ success: true, sent: recipients.length });
  } catch (error) {
    return Response.json({ error: error.message }, { status: 500 });
  }
});