import { createClientFromRequest } from 'npm:@base44/sdk@0.8.25';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { workOrderId, buyerEmail } = await req.json();

    if (!workOrderId || !buyerEmail) {
      return Response.json({ error: 'workOrderId and buyerEmail required' }, { status: 400 });
    }

    // Fetch work order and parts
    const workOrders = await base44.entities.WorkOrder.filter({ id: workOrderId });
    const workOrder = workOrders[0];

    if (!workOrder) {
      return Response.json({ error: 'Work order not found' }, { status: 404 });
    }

    const parts = await base44.entities.PartRequirement.filter({ workOrderId });

    if (parts.length === 0) {
      return Response.json({ error: 'No parts required for this work order' }, { status: 400 });
    }

    // Get equipment details
    const equipment = await base44.entities.Equipment.filter({ id: workOrder.equipmentId });
    const eq = equipment[0] || {};

    // Get mechanic details
    const users = await base44.entities.User.filter({ email: user.email });
    const mechanic = users[0] || {};

    // Build email content
    const partsTable = parts
      .map(p => `
        <tr>
          <td style="padding: 12px; border-bottom: 1px solid #ddd;">${p.partName}</td>
          <td style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center;">${p.quantity}</td>
          <td style="padding: 12px; border-bottom: 1px solid #ddd;">${p.vendor || '—'}</td>
          <td style="padding: 12px; border-bottom: 1px solid #ddd; text-align: right;">$${(p.cost || 0).toFixed(2)}</td>
          <td style="padding: 12px; border-bottom: 1px solid #ddd;">${p.eta || '—'}</td>
          <td style="padding: 12px; border-bottom: 1px solid #ddd; text-align: center;">${p.isCritical ? '🔴 Critical' : '—'}</td>
        </tr>
      `).join('');

    const totalCost = parts.reduce((sum, p) => sum + (p.cost || 0), 0);
    const criticalParts = parts.filter(p => p.isCritical).length;

    const htmlBody = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="utf-8">
        <style>
          body { font-family: Arial, sans-serif; color: #333; }
          .container { max-width: 800px; margin: 0 auto; padding: 20px; }
          .header { background: #f5f5f5; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
          .header h1 { margin: 0 0 10px 0; color: #d97706; font-size: 24px; }
          .header p { margin: 5px 0; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th { background: #f0f0f0; padding: 12px; text-align: left; font-weight: bold; border-bottom: 2px solid #ddd; }
          .summary { background: #e8f5e9; padding: 15px; border-radius: 8px; margin-top: 20px; }
          .summary p { margin: 5px 0; font-weight: bold; }
          .critical { color: #d32f2f; }
          .footer { margin-top: 20px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="container">
          <div class="header">
            <h1>📦 PARTS REQUEST</h1>
            <p><strong>Work Order ID:</strong> ${workOrder.id?.slice(0, 8) || '—'}</p>
            <p><strong>Equipment:</strong> ${workOrder.equipmentName}</p>
            <p><strong>Requested by:</strong> ${mechanic.full_name || user.email}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>

          <h2>Parts Required</h2>
          <table>
            <thead>
              <tr>
                <th>Part Name</th>
                <th style="text-align: center;">Qty</th>
                <th>Vendor</th>
                <th style="text-align: right;">Unit Cost</th>
                <th>ETA</th>
                <th style="text-align: center;">Priority</th>
              </tr>
            </thead>
            <tbody>
              ${partsTable}
            </tbody>
          </table>

          <div class="summary">
            <p>Total Parts Cost: <span style="font-size: 18px;">$${totalCost.toFixed(2)}</span></p>
            <p>${criticalParts > 0 ? `<span class="critical">⚠️ ${criticalParts} critical parts — job blocked until received</span>` : '✓ All parts optional — job can proceed'}</p>
          </div>

          <div class="footer">
            <p><strong>Next Steps:</strong></p>
            <p>Please procure these parts and update their status in AIRepair once received. Mark critical items as high priority.</p>
            <p>This request was auto-generated by AIRepair Mechanics Shop Management System.</p>
          </div>
        </div>
      </body>
      </html>
    `;

    // Send email using RESEND
    const resendResponse = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${Deno.env.get('RESEND_API_KEY')}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'parts-request@airepair.rental',
        to: buyerEmail,
        subject: `Parts Request — ${workOrder.equipmentName} (${workOrder.id?.slice(0, 8) || 'WO'})`,
        html: htmlBody,
      }),
    });

    if (!resendResponse.ok) {
      const err = await resendResponse.text();
      console.error('Resend error:', err);
      return Response.json({ error: 'Failed to send email' }, { status: 500 });
    }

    // Mark parts as "requested"
    for (const part of parts) {
      await base44.entities.PartRequirement.update(part.id, {
        status: part.status === 'unavailable' ? 'on_order' : part.status
      }).catch(() => {});
    }

    return Response.json({
      success: true,
      message: `Parts request sent to ${buyerEmail}`,
      partCount: parts.length,
      totalCost,
      criticalParts,
    });
  } catch (error) {
    console.error('Parts request error:', error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
});